### ISSUE TITLE
Some questions about adding meta coach manual or section on meta coaches -- but how common are they?

### ISSUE THREAD

**Issue by abeld** [DjangoGirls/coach-manual#12]
The organizer manual mentions meta coaches, but the coach manual doesn't. I think having a sentence or two about meta coaches in the coach manual (i.e.: "ask them if you have any technical problems") would be a good idea, as well as having either a separate meta coach manual, or (since it in many respects it overlaps with the coach manual, and wouldn't really be long enough to be a standalone one) a section for meta coaches in the coach manual (with "here are some extra tips for meta coaches" type content).

I have some ideas and can contribute a first draft, but I am uncertain how common meta coaches are: the organizer manual mentions meta coaches as an optional extra, which might mean that these sections wouldn't apply to all workshops. For the wording of these sections, I would like to ask how usual it is to have meta coaches? (So far I participated in three workshops, in all three cases as a meta coach, but my experience might not be representative.) Are there meta coaches for most events, or only in a small fraction? Is having a "if your workshop has meta coaches, then ..." type of conditional in front of these mentions enough or should these parts be worded more optionally?

**Comment by helenst** [comment]
Hi @abeld - thank you for suggesting this!

I'd say metacoaches are common enough that some extra information is useful but uncommon enough that you'd still want the conditional. I'm guessing that at the 10 or so workshops I've been at, maybe half of them had metacoaches. It generally depends on how many people sign up as coaches - if there are enough, we can ask the most experienced ones to metacoach.

To me this feels like an extra chapter in the coaching manual rather than its own manual. There's plenty of content in the coaching manual that is also applicable to metacoaches, probably more than the amount I think could be written for metacoaches alone. I guess a metacoach chapter could point out that those things (e.g. rules, being familiar with the tutorial) are also applicable, and then talk about the differences.

I think this sounds like a great addition to the coach manual anyway! :sparkles:

**Comment by abeld** [comment]
I created a pull request with a first draft. I am somewhat concerned with whether the 'Advice for meta coaches' ended up being too long -- should it be a separate chapter? Also, does the style of the writing fit in with the rest of the manual?

**Comment by aniav** [comment]
I think there was already a good reply on the pull request, but your changes fit the coach manual style. Thank you! 👍
